### ISSUE TITLE
☂️ [umbrella issue] Parent portal

### ISSUE THREAD

**Issue by chrsep** [obserfy/obserfy#142]
Using parent portal, parents would be able to also access obserfy and see reports and update about their children on it directly, on realtime. It should have a dedicated simplified frontend focused for this.

## Features
Planned features for the v0.1:
- [ ] Email invite to parents to join
- [ ] See semester and semi semester report

Future features:
- [ ] See photos
- [ ] See videos
- [ ] See observations in realtime

### Combined with vor, but with dedicated frontend project

**Comment by chrsep** [comment]
gaia is deployed now. we'll track further work items in individual issues.
