### ISSUE TITLE
☂️ [umbrella issue] Landing page

### ISSUE THREAD

**Issue by chrsep** [obserfy/obserfy#143]
This issue tracks all tasks related to the new landing page. Priority follows the order of the lists below.

### Priority 1, Simple straightforward landing page.

We should focus on deploying a simple landing page as fast as possible. The goal is to get more exposure to the project and be able to talk to more people.

- [x]  Create Home page #361
- [x]  Create Contact us page #362
- [x]  Add Google Analytics #364
- [x]  Localize to Indonesia #363

### Priority 2, Product demo and forms

Demo Obserfy's feature and possibly allow people to give feedback about it to us directly on the landing page.

1.  Add short videos demoing features
2. Add forms/surveys to get more feedback and questions from people.

### Priority 3, More content

Add more content explaining the reasoning behind every feature. This would improve SEO and possibly increases the possibility of people trying out obserfy.

1. Explain the ideas behind every feature

**Comment by chrsep** [comment]
done
