### ISSUE TITLE
☂️ [umbrella issue] Improve integration and e2e testing

### ISSUE THREAD

**Issue by chrsep** [obserfy/obserfy#207]
Current testing does not yet cover enough part of our codebase. For now, we should focus on building a good integration and e2e testing so we can cover much of our codebase quickly with test and be more confident on our automated release process.

Without good testing practices, realising frequently and quickly is risky. Chances of us releasing a bad build and having to rollback will be significantly higher. E2E tests are handled using cypress. Rest API integration tests are done using `go test`.

### Targets
- Code coverage above **70%**
- Cover all user's happy paths on e2e
- Have a good API test so we can quickly notice changes in API behaviour

### Todo
- [x] [e2e] Edit and view Curriculum happy path
- [ ] [api] User related API
- [ ] [api] Student related API
- [x] [api] School related API
- [ ] [api] Observations related API
- [ ] [api] Auth related API
- [ ] [api] Curriculum related API
- [ ] [api] Observations related API

**Comment by chrsep** [comment]
we'll track this using codecov from now since the work items will continue to increase as obserfy evolves.
