### ISSUE TITLE
Allow students to be set as inactive

### ISSUE THREAD

**Issue by chrsep** [obserfy/obserfy#522]
Currently, all students are being shown on obserfy, whether they are currently active or not. This spams the app with inactive students that makes navigating harder.

User can delete the students but this is not optimal because this way the school will lose all data related to that student when they postpone their enrollment. A better way would be for the school to be able to set their students as inactive. Inactive students wouldn't be shown anywhere on the app accept in the settings section.

### TODO
- [x] Update `PATCH` `/students/{studentId}` to accept `active: boolean`  properties
- [x] Update usePatchStudentApi hook to accept active attribute in its parameter
- [x] Add list of students page on settings that allows user to see all active and inactive students and set their active attribute to false or true
- [x] Add "set as inactive" button on `PageStudentProfile`

### Additional details
Overview of reuseable components available on [sb.obserfy.com](https://sb.obserfy.com)

#### Wireframe (3rd todo, settings -> students)
![excalidraw-2020314193352(4)](https://user-images.githubusercontent.com/8491552/85548499-34078f80-b649-11ea-8f86-87cb883047a2.png)

#### Wireframe (4th todo, PageStudentProfile)
![excalidraw-2020314193352(5)](https://user-images.githubusercontent.com/8491552/85549089-d293f080-b649-11ea-97ee-dc67ad1c6f29.png)

**Comment by christianto88** [comment]
completed by @christianto88 :clap::clap::clap::clap::clap:
