### ISSUE TITLE
Implement lesson plan in gaia

### ISSUE THREAD

**Issue by chrsep** [obserfy/obserfy#622]
Currently gaia just shows an empty page. Since lesson plans is now implemented on vor, we could start implementing lesson plans in Gaia.

#### Todo:
- [x] Add `GET` `/api/student/lessonPlans` on gaia (should accepts date query).
- [x] Add `useGetLessonPlans` hook on gaia
- [x] Show lesson plans on gaia home page.
