### ISSUE TITLE
Show who posted a lesson plan

### ISSUE THREAD

**Issue by chrsep** [obserfy/obserfy#659]
We need to know who posted a lesson plan.

### todo
- [x] Add user id to lesson plan details table
- [x] Save userid when saving lesson plan
- [x] Returns user name on `GET` `/school/{schoolId}/plans`
- [x]  Returns user name on `GET` `/students/{studentId}/plans` 
- [x] Update UI to show user name

**Comment by christianto88** [comment]
What does it mean by "posted"? We add the userId when its first created or when we update the lesson plan too?

**Comment by chrsep** [comment]
Only when it is first created. I think tracking who updated the plans would be a lot more complicated.

**Comment by christianto88** [comment]
Got it 👍

**Comment by christianto88** [comment]
@chrsep Where is the routes `GET /school/{schoolId}/plans` called? On what page?

**Comment by chrsep** [comment]
Oh, I just realized, `GET /school/{schoolId}/plans` is used on PagePlans on the frontend, but that is currently temporarily removed because of recent shifting design requirements. Plans needed to be managed on a student by student basis, instead of many students sharing the same lesson plans.

This means `GET` `/students/{studentId}/plans` also need to be updated.

**Comment by chrsep** [comment]
close by #735
